name: DeployToS3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: AWS set Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: 'ap-southeast-2'
          role-to-assume: 'arn:aws:iam::976193267898:role/full-access-for-mentsuke-simulator'
    
    - name: Build Static Files
      run: cd ./src; npm run buildtodeploy;

    - name: Build and Deploy to S3
      run: aws s3 cp .output s3://mentsuke-simulator-pipe --region ap-southeast-2
